### ISSUE TITLE
TRUSTY_ROUTE endpoints not working as expected

### ISSUE THREAD

**Issue by Awayah** [trustyai-explainability/odh-trustyai-demos#12]
Hi, I have successfully followed the 2-Bias Monitoring Tutorial upto: **Send Training Data to Models section**. The trusty AI service sees ~2000 observations against each model, which also reflects in the Metrics Dashboard.

However, when I try to query the trusty service endpoints using a curl request eg: `curl $TRUSTY_ROUTE/info | jq ".[0].data"` I get a certificate error: 

```
$ curl $TRUSTY_ROUTE/info | jq ".[0].data"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (60) schannel: SEC_E_UNTRUSTED_ROOT (0x80090325) - The certificate chain was issued by an authority that is not trusted.
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.

```

And if I try to bypass this with --insecure and try without jq, I get an HTML response. I copied this HTML response and this is what the page is, so it is asking for a login before it can access the endpoint:
![image](https://github.com/trustyai-explainability/odh-trustyai-demos/assets/138879962/5f1bc10d-f208-4bcd-9b38-26a6bac34ea4)

 So I am confused here as to why it's not working for me. Subsequently the mapping script and the spd endpoint calls are also not working as expected. Can you please provide some guidance? Which checks can I perform to verify if everything is working as it should be.

**Comment by RobGeada** [comment]
Hi @Awayah, sorry about that, the tutorials have been updated to describe how to authenticate to the TrustyAI endpoints:

```bash
export TOKEN=$(oc whoami -t)
curl -H "Authorization: Bearer ${TOKEN}" $TRUSTY_ROUTE/info
```
