### ISSUE TITLE
Constraint violation checking model fairness

### ISSUE THREAD

**Issue by adrien-legros** [trustyai-explainability/odh-trustyai-demos#4]
Following the demo up to: https://github.com/trustyai-explainability/odh-trustyai-demos/tree/main/2-BiasMonitoring#check-model-fairness

Getting:
```
{"title":"Constraint Violation","status":400,"violations":[{"field":"response.request.demo-loan-nn-onnx-alpha.Will Default?","message":"No output found with name=Will Default?"},{"field":"response.request","message":"The supplied metric request details are not valid."},{"field":"response.request.demo-loan-nn-onnx-alpha.Is Male-Identifying?","message":"No protected attribute found with name=Is Male-Identifying?"}]}
```

I tried to change `protectedAttribute` with `customer_data_input-3` and `outcomeName` with `predict`. Doing that I get this error: 
```
Error calculating metric: Column -1 outside dataframe bounds (0, 12)
```

The trustyaiServiceImage is `quay.io/trustyai/trustyai-service:latest` and the operator image is `registry.redhat.io/rhods/odh-trustyai-service-operator-rhel8` provided by RHOAI

Output of $TRUSTY_ROUTE/info: [log.json](https://github.com/trustyai-explainability/odh-trustyai-demos/files/13717461/log.json)

**Comment by RobGeada** [comment]
Yep, it looks like there's an issue with the bias endpoints not checking the name mapped fields, and therefore throwing validation errors. Meanwhile, the TrustyAI service sees the name mappings, meaning the original field names are not usable either. I'll fix the name mapping validation, but as a workaround, you can delete the non-working name mappings via:

```
MODEL_ALPHA=demo-loan-nn-onnx-alpha
MODEL_BETA=demo-loan-nn-onnx-beta
TRUSTY_ROUTE=https://$(oc get route/trustyai-service --template={{.spec.host}})

for model in $MODEL_ALPHA $MODEL_BETA; do
  curl -sk  -X POST --location $TRUSTY_ROUTE/info/names \
      -H "Content-Type: application/json" \
      -d "{
          \"modelId\": \"$model\",
          \"inputMapping\":{},
          \"outputMapping\":{}
      }"
done
```

**Comment by adrien-legros** [comment]
Thanks a lot, the workaround works well
